[package]
name = "kestrel"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
inkwell = {git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm10-0"]}
guess_host_triple = "0.1.3"
colored = "2.0.0"
itertools = "0.10.5"
unicode-width = "0.1.7"
Inflector = "*"